# for loop

In [1]:
seq = [11, 2, 3,4 , 5, 6]
for num in seq:
    print('hello')

hello
hello
hello
hello
hello
hello


# while loop

In [2]:
i = 1
while i < 5:
    print(i)
    i = i + 1

1
2
3
4


In [3]:
for x in range(0,5):     # this prints 0 to 4
    print(x)
    

0
1
2
3
4


In [4]:
range(0,5)


range(0, 5)

In [5]:
#if want above statement to the list
list(range(0, 5))

[0, 1, 2, 3, 4]

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
x = [1, 2, 3, 4]

output = []

for num in x:
    output.append(num**2)
    
print(output)


[1, 4, 9, 16]


# def

In [8]:
def my_func(name = ' shravani'):
    print('Hello' +name)

In [9]:
my_func() # it takes default name as shravani if we dont give any name

Hello shravani


In [10]:
my_func(name = ' abhi') #name changes to shravani beacuase we are changing the name

Hello abhi


In [11]:
my_func('  krishna')

Hello  krishna


In [12]:
def square(num):
    return num**2

In [13]:
x = square(19)

In [14]:
x

361

In [15]:
def square(num):
    x = num**2
    print(x)
    
square(2)
      
     

4


In [16]:
def times(var):
    return var*2
times(3)

6

In [17]:
# how can we do the same action on the list
y = [1, 2, 3, 4, 5, 6]

list(map(lambda num : num*2, y)) # num is the each item in the list y


[2, 4, 6, 8, 10, 12]

In [18]:
  def times(var) : return var*2  
  # see below how can we write same function using lambda

In [19]:
times(5) 

10

In [20]:
t = lambda var : var*2
t(5)

10

In [21]:
# how to filter the even numbers from the list

list(filter(lambda num: num%2 == 0, y))

[2, 4, 6]

# lower

In [22]:
greeting = 'Hello my name is shravani'

In [23]:
greeting.lower()

'hello my name is shravani'

In [24]:
greeting.upper()

'HELLO MY NAME IS SHRAVANI'

In [25]:
greeting.split()

['Hello', 'my', 'name', 'is', 'shravani']

In [26]:
x = 'Go Sports! #sports'
x.split()

['Go', 'Sports!', '#sports']

In [27]:
x.split('#') # so we are deleting the # from the sentence

['Go Sports! ', 'sports']

In [28]:
x.split('#')[1]

'sports'

In [29]:
x.split('#')[0]

'Go Sports! '

In [30]:
d = {'k1' : 1, 'k2' : 2}

In [31]:
d

{'k1': 1, 'k2': 2}

In [32]:
d.keys()

dict_keys(['k1', 'k2'])

In [33]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [34]:
d.values()

dict_values([1, 2])

In [35]:
x = [1, 2, 3]
y = x.pop()

In [36]:
x

[1, 2]

In [37]:
y

3

In [38]:
y = x.pop(0)

# NUMPY

In [39]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



# Numpy Array



In [40]:
import numpy as np


In [41]:
x = np.array([2, 3, 4])  # this is actual form of 1d array
x   

array([2, 3, 4])

In [42]:
print(x) #array don't have the , in between, but in case of list we do

[2 3 4]


In [43]:
x[2]

4

In [44]:
type(x)

numpy.ndarray

In [45]:
# 2D
y = np.array([[1,2,3], [4, 5, 6]]) #syntax
y

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
print(y)

[[1 2 3]
 [4 5 6]]


In [47]:
y.ndim  # This say which dimension is this

2

In [48]:
z = np.array([[[1,2,3], [4, 5, 6], [7, 8, 9]]]) 
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [49]:
z.ndim

3

In [50]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones((3, 4, 2), dtype = int) # this shows 3 2d arrays and 4 rows with 2 columns


array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [54]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [55]:
a = np.random.random((2,5))
a
print(a)

[[0.17253395 0.45606425 0.48076063 0.77401098 0.61411828]
 [0.38943614 0.13821847 0.62023416 0.67191969 0.62818794]]


In [56]:
a = np.random.randint(2,10,size=(3,4))
print(a) # 2, 10 are the range and 3, 4 are size of the matrix

[[7 5 5 7]
 [8 9 4 6]
 [2 2 3 8]]


In [57]:
np.sum([[2000, 10],[8000,48]],axis =0) #when axis=0 rows starts to sumup

array([10000,    58])

In [58]:
print(np.sum([[2000, 10],[8000,48]],axis =1))

[2010 8048]


In [59]:
shravani_bio=np.array(['26','pinky','1998','shravani','pinky','chitty','supriya','yellampeta','khammam','married'])
print(shravani_bio)



['26' 'pinky' '1998' 'shravani' 'pinky' 'chitty' 'supriya' 'yellampeta'
 'khammam' 'married']


In [60]:
shravani_bio[2:4]

array(['1998', 'shravani'], dtype='<U10')

In [61]:
np.where(shravani_bio == 'pinky') 
# it shows at what location pinnky is present


(array([1, 4]),)

# concatenation is a sometype of integration 


In [62]:
x=np.array([[1, 2, 3], [4, 5, 6]])
y=np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate((x, y), axis = 0)


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate((x, y), axis = 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
x=np.array([[1, 2, 3], [4, 5, 6]]) #2D
y=np.array([1, 2, 3]) # 1D
y.ndim


1

In [65]:
y=y.reshape(1,3)  # we are reshaping 1-d to 2-d
y.ndim
y

array([[1, 2, 3]])

In [66]:
np.concatenate((x, y), axis = 0)


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

# create a array of 10 


In [67]:
np.zeros(10) #create a array of zeros 10 times

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.ones(10) #create a array of ones 10 times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.ones(10) * 5
#create a array of fives 10 times

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [70]:
np.arange(10, 51) # create the number 10 to 51

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [71]:
np.arange(10, 51, 2)
 # from 10 to 50 take all the even numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [72]:
#create a 3X3 matrix with range 0 to 8
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
# i need above array in 3 x3 matrix
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.random.rand(1)  # chooses 0 to 1

array([0.11700762])

In [76]:
a = np.random.randn(25)  # so we need 25 random numbers so we do use randn

In [77]:
a.reshape(5,5)

array([[ 1.85652501,  0.28025501, -0.3429292 , -0.16806923,  1.29825188],
       [ 0.02062295,  3.33735237, -0.82781563,  1.16983372,  0.40408941],
       [-0.38337451,  0.25787854,  0.67035777, -0.1115699 , -1.0368897 ],
       [-0.55602605,  1.18901644, -0.86269366,  0.7825081 , -0.10522633],
       [-0.90052536,  0.95362599,  1.0430255 ,  1.71059785, -0.59606494]])

# creating a matrix

In [78]:
np.arange(1, 101).reshape(10, 10)/100
# here we are taking range og 1 to 100 and 10 by 1 matrix so we are diving by 100 to get decimal

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [79]:
np.linspace(0.01, 1, 100).reshape(10, 10) # similar to above code

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [80]:
np.linspace(0, 1, 20) # so here we are getting values from 0 to 1 with space of 20

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NUMPY iNDEXING  AND SELECTION

In [81]:
Mat = np.arange(1, 26).reshape(5, 5)
Mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
Mat[2:,1:] # i want to exact the below values

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [83]:
# in need aonly 20 from the mat
Mat[3][4]


20

In [84]:
Mat[3, 4]

20

In [85]:
Mat[0:3,1:2 ]
# i need below matrix

array([[ 2],
       [ 7],
       [12]])

In [86]:
Mat[4:,]

array([[21, 22, 23, 24, 25]])

In [87]:
Mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# sum of all the values in mat

In [88]:
Mat.sum() 

325

In [89]:
np.std(Mat)  # to find the standard derviation


7.211102550927978

In [90]:
Mat.std()

7.211102550927978

In [91]:
Mat.sum(axis = 0) # all the colums in the mat is to be summed

array([55, 60, 65, 70, 75])

# PANDAS

In [92]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [93]:
import pandas as pd

In [94]:
labels = ['a', 'b', 'c']
my_data = [10, 20, 30]
arr = np.array(my_data)
d = {'a': 10, 'b':20, 'c':30}


In [95]:
print(labels)
print(my_data)
print(arr)
print(d)



['a', 'b', 'c']
[10, 20, 30]
[10 20 30]
{'a': 10, 'b': 20, 'c': 30}


# Lets see how to create series

In [96]:
pd.Series(data= my_data)

0    10
1    20
2    30
dtype: int64

In [97]:
pd.Series(data=my_data,index=labels)


a    10
b    20
c    30
dtype: int64

In [98]:
pd.Series(my_data, labels)



a    10
b    20
c    30
dtype: int64

In [99]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [100]:
ser = pd.Series([1, 2, 3],['pink','yelo','blue'])
ser



pink    1
yelo    2
blue    3
dtype: int64

In [101]:
ser1 = pd.Series(['pink','yelo','umber'],[1, 2, 3])
ser1

1     pink
2     yelo
3    umber
dtype: object

In [102]:
ser['blue']

3

In [103]:
ser2 = pd.Series(data = labels)
ser2


0    a
1    b
2    c
dtype: object

In [104]:
ser1 + ser

1       NaN
2       NaN
3       NaN
blue    NaN
pink    NaN
yelo    NaN
dtype: object

# Create DataFrames

In [105]:
import numpy as np
import pandas as pd

In [106]:
from numpy.random import randn

In [107]:
np.random.seed(101)

In [108]:
df = pd.DataFrame(randn(5,3),['A','B','C','D','E'],['W','X',"Y"])
df
# randn is the command selects the random numbers

W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001
E  0.188695 -0.758872 -0.933237

In [109]:
df['W'] 
# in this case we are calling one column so we are geting series

A    2.706850
B    0.503826
C   -0.848077
D    0.740122
E    0.188695
Name: W, dtype: float64

In [110]:
type(df['W'])

pandas.core.series.Series

In [111]:
df.W # similar to df['W'] mostly use that method than this

A    2.706850
B    0.503826
C   -0.848077
D    0.740122
E    0.188695
Name: W, dtype: float64

In [112]:
df[['W','X']]
# we are asking multiply column we get the dataframe

W         X
A  2.706850  0.628133
B  0.503826  0.651118
C -0.848077  0.605965
D  0.740122  0.528813
E  0.188695 -0.758872

In [113]:
# creating new column
df['new'] = df['W']+ df['Y']

In [114]:
df

W         X         Y       new
A  2.706850  0.628133  0.907969  3.614819
B  0.503826  0.651118 -0.319318  0.184508
C -0.848077  0.605965 -2.018168 -2.866245
D  0.740122  0.528813 -0.589001  0.151122
E  0.188695 -0.758872 -0.933237 -0.744542

In [115]:
df.drop('new',axis = 1,inplace =True)   

In [116]:
df.drop('E')

W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [117]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Name: A, dtype: float64

In [118]:
df.loc['A','Y']

0.9079694464765431

In [119]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.503826 -0.319318

In [120]:
df > 0  # value greater than 0

W      X      Y
A   True   True   True
B   True   True  False
C  False   True  False
D   True   True  False
E   True  False  False

In [121]:
booldf = df > 0 

In [122]:
df[booldf] # gives all the positive values and negative values as NaN

W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118       NaN
C       NaN  0.605965       NaN
D  0.740122  0.528813       NaN
E  0.188695       NaN       NaN

In [123]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [124]:
df[df["W"]>0]  #only returns the row which is true

W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
D  0.740122  0.528813 -0.589001
E  0.188695 -0.758872 -0.933237

In [125]:
df[df['X']<0]

W         X         Y
E  0.188695 -0.758872 -0.933237

In [126]:
resultdf = df[df["W"]>0]  # here we are getting w values greater than 0
resultdf


W         X         Y
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
D  0.740122  0.528813 -0.589001
E  0.188695 -0.758872 -0.933237

In [127]:
resultdf['X'] # from the result get the x values

A    0.628133
B    0.651118
D    0.528813
E   -0.758872
Name: X, dtype: float64

In [128]:
df[df['W']>0]['X'] # similar to above code but in simpilar way

A    0.628133
B    0.651118
D    0.528813
E   -0.758872
Name: X, dtype: float64

In [129]:
df[df['W']>0][['X', 'Y']]

X         Y
A  0.628133  0.907969
B  0.651118 -0.319318
D  0.528813 -0.589001
E -0.758872 -0.933237

In [130]:
df[(df['W']>0) & (df['Y']> 0.8)]


W         X         Y
A  2.70685  0.628133  0.907969

In [131]:
df.reset_index() # index is converted to a column

index         W         X         Y
0     A  2.706850  0.628133  0.907969
1     B  0.503826  0.651118 -0.319318
2     C -0.848077  0.605965 -2.018168
3     D  0.740122  0.528813 -0.589001
4     E  0.188695 -0.758872 -0.933237

In [132]:
newind = 'IN US UK  EUR PAK'.split()



In [133]:
newind


['IN', 'US', 'UK', 'EUR', 'PAK']

In [134]:
df['states'] = newind # we are adding new column states

In [135]:
df

W         X         Y states
A  2.706850  0.628133  0.907969     IN
B  0.503826  0.651118 -0.319318     US
C -0.848077  0.605965 -2.018168     UK
D  0.740122  0.528813 -0.589001    EUR
E  0.188695 -0.758872 -0.933237    PAK

In [197]:
outside = ['g1','g1','g1','g2','g2','g2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [198]:
outside

['g1', 'g1', 'g1', 'g2', 'g2', 'g2']

In [199]:
inside

[1, 2, 3, 1, 2, 3]

 hier_index

In [200]:
hier_index

MultiIndex([('g1', 1),
            ('g1', 2),
            ('g1', 3),
            ('g2', 1),
            ('g2', 2),
            ('g2', 3)],
           )

In [201]:
df = pd.DataFrame(randn(6,2), hier_index,['A','B'])

In [202]:
df

A         B
g1 1  0.358941 -1.080471
   2  0.902398  0.161781
   3  0.833029  0.975720
g2 1 -0.388239  0.783316
   2 -0.708954  0.586847
   3 -1.621348  0.677535

In [203]:
df.loc['g1']

A         B
1  0.358941 -1.080471
2  0.902398  0.161781
3  0.833029  0.975720

In [204]:
df.loc['g1']['A']


1    0.358941
2    0.902398
3    0.833029
Name: A, dtype: float64

In [205]:
df.loc['g1'].loc[1]

A    0.358941
B   -1.080471
Name: 1, dtype: float64

In [206]:
df.index.names = ['Groups','Num']
# we are fixing the index

In [207]:
df

A         B
Groups Num                    
g1     1    0.358941 -1.080471
       2    0.902398  0.161781
       3    0.833029  0.975720
g2     1   -0.388239  0.783316
       2   -0.708954  0.586847
       3   -1.621348  0.677535

In [212]:
df.loc['g2'].loc[2,'B']



0.586847295403904

In [213]:
df.loc['g1']

A         B
Num                    
1    0.358941 -1.080471
2    0.902398  0.161781
3    0.833029  0.975720

In [221]:
# xs--- cross section which has many uses lets see below , it decreases the long codes
df.xs(1,level = 'Num')


A         B
Groups                    
g1      0.358941 -1.080471
g2     -0.388239  0.783316

# Pandas - Missing Data



In [222]:
import numpy as np
import pandas as pd

In [228]:
d = {'A':[1, 2, np.nan],'B':[5,np.nan,np.nan],'C' :[1, 2, 3]}


In [229]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [230]:
df = pd.DataFrame(d)


In [231]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [233]:
# drop Nan
df.dropna(axis = 1)


C
0  1
1  2
2  3

In [234]:
df.dropna(axis = 0)



A    B  C
0  1.0  5.0  1

In [235]:
df.dropna() #it defaultly takes axis= 0 

A    B  C
0  1.0  5.0  1

In [241]:
df.dropna(thresh=2)
# it gives atleast two columns contains the values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [242]:
df.fillna(value='NON-ZERO')
# here we can fill a vlue in place of NaN

A         B  C
0       1.0       5.0  1
1       2.0  NON-ZERO  2
2  NON-ZERO  NON-ZERO  3

In [246]:
df.fillna(value= df.mean())
# mostly we fill mean value in NaN place

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

# Groupby with pandas


In [248]:
import numpy as np
import pandas as pd


In [251]:
data= {'company':['goog','goog','msft','msft','fb','fb'],
      'person':['sam','jan','jam','cam','mel','gum'],
      'sales':[100, 209,90,60,70,100]}

In [252]:
data

{'company': ['goog', 'goog', 'msft', 'msft', 'fb', 'fb'],
 'person': ['sam', 'jan', 'jam', 'cam', 'mel', 'gum'],
 'sales': [100, 209, 90, 60, 70, 100]}

In [253]:
df = pd.DataFrame(data)
df

company person  sales
0    goog    sam    100
1    goog    jan    209
2    msft    jam     90
3    msft    cam     60
4      fb    mel     70
5      fb    gum    100

In [254]:
df.groupby('company')
# we need to assign to something

In [255]:
bycomp = df.groupby('company')
bycomp 

In [256]:
bycomp.mean()

sales
company       
fb        85.0
goog     154.5
msft      75.0

In [257]:
bycomp.std()


sales
company           
fb       21.213203
goog     77.074639
msft     21.213203

In [258]:
bycomp.sum()

sales
company       
fb         170
goog       309
msft       150

In [259]:
bycomp.sum().loc['fb']

sales    170
Name: fb, dtype: int64

In [260]:
bycomp.count() # it shows number of company has

person  sales
company               
fb            2      2
goog          2      2
msft          2      2

In [261]:
bycomp.max()

person  sales
company              
fb         mel    100
goog       sam    209
msft       jam     90

In [262]:
bycomp.min()


person  sales
company              
fb         gum     70
goog       jan    100
msft       cam     60

In [264]:
bycomp.describe()
# this gives the whole information

sales                                                       
        count   mean        std    min     25%    50%     75%    max
company                                                             
fb        2.0   85.0  21.213203   70.0   77.50   85.0   92.50  100.0
goog      2.0  154.5  77.074639  100.0  127.25  154.5  181.75  209.0
msft      2.0   75.0  21.213203   60.0   67.50   75.0   82.50   90.0

In [265]:
bycomp.describe().transpose()

company              fb        goog       msft
sales count    2.000000    2.000000   2.000000
      mean    85.000000  154.500000  75.000000
      std     21.213203   77.074639  21.213203
      min     70.000000  100.000000  60.000000
      25%     77.500000  127.250000  67.500000
      50%     85.000000  154.500000  75.000000
      75%     92.500000  181.750000  82.500000
      max    100.000000  209.000000  90.000000

In [266]:
bycomp.describe().transpose()['goog'] #gives the info of goog

sales  count      2.000000
       mean     154.500000
       std       77.074639
       min      100.000000
       25%      127.250000
       50%      154.500000
       75%      181.750000
       max      209.000000
Name: goog, dtype: float64

# concat

In [ ]:
# if you have three different dataframes to join them use concat
# pd. concat([df1,df2,df3], axis = 0)
#               or
# pd. concat([df1,df2,df3], axis = 1)    


# merging and joining

# Operations



In [269]:
import numpy as np
import pandas as pd



In [271]:
df = pd.DataFrame({'col1':[1, 2, 3,4],
                   'col2':[444,555,666,444],
                    'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [272]:
# finding unique values in the dataframe
df['col2'].unique() 
# is shows uniquie values but below we do see number of unique values

array([444, 555, 666])

In [273]:
df['col2'].nunique()
# this shows number of unique values

3

In [274]:
df['col2'].value_counts()
# this return the number of types the value is present

444    2
555    1
666    1
Name: col2, dtype: int64

In [277]:
# selecting the data
df['col1']>2  # is returns the boolen values

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [278]:
df[df['col1']>2] # this return the value

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [279]:
# applied method
def time2(x):
    return x*2


In [281]:
df['col1'].apply(time2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [283]:
df['col2'].apply(lambda x:x*2)


0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [284]:
#df.drop('col1',axis=1,implace=true) 
# to drop something

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [285]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [286]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [288]:
df.sort_values(by = 'col2') # to sort the values

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [289]:
df.isnull() # to find the null value

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

# pivot table

In [292]:
data = {'A' : ['foo','foo','foo','bar','bar','bar'],
       'B' : ['one','one', 'two','two','one','one'],
        'C': ['x','y','x','y','x','y'],
        'D': [1, 3, 2,5, 4, 1]}
df = pd.DataFrame(data)

In [293]:
df


A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [294]:
df.pivot_table(values='D',index= ['A','B'], columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# input and output(csv, excel, Html, sql)

In [295]:
# pip install sqlalchemy ---- for sql
# " "   "  "    lxml.  --------for excel
#  " "   "  "  html5lib -------for html
#  " "   "  "  beautifulsoup4

In [296]:
import pandas as pd

In [297]:
pwd

'/Users/shravani'

In [300]:
pd.read_csv('example')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [302]:
df = pd.read_csv('example')

In [305]:
df.to_csv('My_Output', index= False)

In [306]:
pd.read_csv('My_Output')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [309]:
pd.read_excel('Excel_sample.xlsx')


Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [314]:
 df.to_excel('Excel_sample1.xlsx')
# we are chamging csv file to excel

pandas.core.frame.DataFrame

# SF sALARIES EXERCISE --- KAGGLE

In [6]:
import pandas as pd
sal = pd.read_csv('Salaries.csv')

/var/folders/v0/r65ddn057c5_gzd01d2yz8yr0000gn/T/ipykernel_86736/185440898.py:2: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv')


In [8]:
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [9]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [10]:
sal.info() # to check how many entries are present

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [15]:
# we need average Base Pay----- first we need to grab base pay column
# mean is nothing but average
sal['BasePay'].mean()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [16]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
# the basepay is in object data type, i want to convert to numeric

In [17]:
sal.info() # to check how many entries are present

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(4), int64(2), object(7)
memory usage: 14.7+ MB


In [18]:
sal['BasePay'].mean() 
#unable to do in above because that is in string form sting can't give as the mean value do we are converting string to numeris

66325.44884050643

In [23]:
sal['OvertimePay'].max()  # find the maximum over time pay




TypeError: '>=' not supported between instances of 'float' and 'str'

In [24]:
sal[' OvertimePay'] = pd.to_numeric(sal[ 'OvertimePay'], errors='coerce').isna()

In [25]:
sal['OvertimePay'].max()

TypeError: '>=' not supported between instances of 'float' and 'str'

In [26]:
# print what is the job title of joseph
sal['EmployeeName'] == 'JOSEPH DRISCOLL' 
#This checks the codition where it is present to get exactly use below code

0         False
1         False
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

In [27]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL' ]

Id     EmployeeName                   JobTitle    BasePay OvertimePay  \
24  25  JOSEPH DRISCOLL  CAPTAIN, FIRE SUPPRESSION  140546.86    97868.77   

    OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
24  31909.28      NaN  270324.91         270324.91  2011    NaN   

           Agency Status   OvertimePay  
24  San Francisco    NaN         False

In [28]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL' ]['JobTitle']
#only job title

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

# vizualization ---- Matplotlib


In [29]:
pip install matplotlib


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import matpotlin.pyplot as plt
